export const ROLES = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  EDITOR: "EDITOR",
  USER: "USER",
  MEMBER: "MEMBER",
  AFFILIATE: "AFFILIATE",
  // grit:role-constants
} as const;

export const API_ROUTES = {
  AUTH: {
    LOGIN: "/api/auth/login",
    REGISTER: "/api/auth/register",
    REFRESH: "/api/auth/refresh",
    LOGOUT: "/api/auth/logout",
    ME: "/api/auth/me",
    FORGOT_PASSWORD: "/api/auth/forgot-password",
    RESET_PASSWORD: "/api/auth/reset-password",
    OAUTH: {
      GOOGLE: "/api/auth/oauth/google",
      GITHUB: "/api/auth/oauth/github",
    },
  },
  USERS: {
    LIST: "/api/users",
    GET: (id: number) => `/api/users/${id}`,
    UPDATE: (id: number) => `/api/users/${id}`,
    DELETE: (id: number) => `/api/users/${id}`,
  },
  UPLOADS: {
    CREATE: "/api/uploads",
    LIST: "/api/uploads",
    GET: (id: number) => `/api/uploads/${id}`,
    DELETE: (id: number) => `/api/uploads/${id}`,
  },
  AI: {
    COMPLETE: "/api/ai/complete",
    CHAT: "/api/ai/chat",
    STREAM: "/api/ai/stream",
  },
  ADMIN: {
    JOBS_STATS: "/api/admin/jobs/stats",
    JOBS_LIST: (status: string) => `/api/admin/jobs/${status}`,
    JOBS_RETRY: (id: string) => `/api/admin/jobs/${id}/retry`,
    JOBS_CLEAR: (queue: string) => `/api/admin/jobs/queue/${queue}`,
    CRON_TASKS: "/api/admin/cron/tasks",
  },
  PROFILE: {
    GET: "/api/profile",
    UPDATE: "/api/profile",
    DELETE: "/api/profile",
  },
  BLOGS: {
    LIST: "/api/blogs",
    GET: (slug: string) => `/api/blogs/${slug}`,
    ADMIN_LIST: "/api/admin/blogs",
    CREATE: "/api/admin/blogs",
    UPDATE: (id: number) => `/api/admin/blogs/${id}`,
    DELETE: (id: number) => `/api/admin/blogs/${id}`,
  },
  CONTACTS: {
    LIST: "/api/contacts",
    GET: (id: number) => `/api/contacts/${id}`,
    CREATE: "/api/contacts",
    UPDATE: (id: number) => `/api/contacts/${id}`,
    DELETE: (id: number) => `/api/contacts/${id}`,
    ACTIVITIES: (id: number) => `/api/contacts/${id}/activities`,
  },
  TAGS: {
    LIST: "/api/tags",
    CREATE: "/api/tags",
    DELETE: (id: number) => `/api/tags/${id}`,
  },
  MEDIA: {
    UPLOAD: "/api/media",
    LIST: "/api/media",
    GET: (id: number) => `/api/media/${id}`,
    UPDATE: (id: number) => `/api/media/${id}`,
    DELETE: (id: number) => `/api/media/${id}`,
  },
  PAGES: {
    LIST: "/api/pages",
    HIERARCHY: "/api/pages/hierarchy",
    GET: (id: number) => `/api/pages/${id}`,
    CREATE: "/api/pages",
    UPDATE: (id: number) => `/api/pages/${id}`,
    DELETE: (id: number) => `/api/pages/${id}`,
    PUBLIC_GET: (slug: string) => `/api/pages/${slug}`,
  },
  POSTS: {
    LIST: "/api/posts",
    GET: (id: number) => `/api/posts/${id}`,
    CREATE: "/api/posts",
    UPDATE: (id: number) => `/api/posts/${id}`,
    DELETE: (id: number) => `/api/posts/${id}`,
    PUBLIC_LIST: "/api/posts",
    PUBLIC_GET: (slug: string) => `/api/posts/${slug}`,
    JSONLD: (slug: string) => `/api/posts/${slug}/jsonld`,
    RSS: "/api/rss.xml",
  },
  POST_CATEGORIES: {
    LIST: "/api/post-categories",
    CREATE: "/api/post-categories",
    UPDATE: (id: number) => `/api/post-categories/${id}`,
    DELETE: (id: number) => `/api/post-categories/${id}`,
  },
  POST_TAGS: {
    LIST: "/api/post-tags",
    CREATE: "/api/post-tags",
    DELETE: (id: number) => `/api/post-tags/${id}`,
  },
  MENUS: {
    LIST: "/api/menus",
    GET: (id: number) => `/api/menus/${id}`,
    CREATE: "/api/menus",
    UPDATE: (id: number) => `/api/menus/${id}`,
    DELETE: (id: number) => `/api/menus/${id}`,
    CREATE_ITEM: (menuId: number) => `/api/menus/${menuId}/items`,
    UPDATE_ITEM: (menuId: number, itemId: number) => `/api/menus/${menuId}/items/${itemId}`,
    DELETE_ITEM: (menuId: number, itemId: number) => `/api/menus/${menuId}/items/${itemId}`,
    REORDER: (menuId: number) => `/api/menus/${menuId}/reorder`,
    BY_LOCATION: (location: string) => `/api/menus/location/${location}`,
  },
  HEALTH: "/api/health",
  // grit:api-routes
} as const;
